rename tyfsedit

diff --git a/mydos/format b/mydos/format
--- a/mydos/format
+++ b/mydos/format
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Format a disk with tyfs.
+# Format a disk with vifs.
 #
 # Run with -h for usage.
 # Default values: 1 reserved sector, max file size 2 blocks
@@ -27,8 +27,8 @@ shift $((OPTIND -1))
 
 IMG=$1
 
-if ! test -f tyfsedit ; then
-    echo "tyfsedit not found (have you built it?)"
+if ! test -f vifsedit ; then
+    echo "vifsedit not found (have you built it?)"
     exit 1
 fi
 
@@ -51,5 +51,5 @@ quit
 EOF
 )
 
-echo "$cmd" | ./tyfsedit
+echo "$cmd" | ./vifsedit
 
diff --git a/mydos/put b/mydos/put
--- a/mydos/put
+++ b/mydos/put
@@ -23,8 +23,8 @@ shift $((OPTIND -1))
 FILE=$1
 IMG=$2
 
-if ! test -f tyfsedit ; then
-    echo "tyfsedit not found (have you built it?)"
+if ! test -f vifsedit ; then
+    echo "vifsedit not found (have you built it?)"
     exit 1
 fi
 
@@ -55,5 +55,5 @@ quit
 EOF
 )
 
-echo "$cmd" | ./tyfsedit
+echo "$cmd" | ./vifsedit
 
